"""Programguider för SIE-export. Menyvägarna bygger på leverantörernas egna hjälpsidor (se källor).
Kontrollera mot källorna när en guide uppdateras."""

GUIDER = [
    {"slug": "sie-fil-fortnox", "namn": "Fortnox",
     "ingress": "I Fortnox Bokföring tar du ut SIE-filen från exportfunktionen högst upp i programmet. Välj SIE4, som innehåller alla verifikationer, och hela räkenskapsåret.",
     "steg": ["Öppna Fortnox Bokföring för rätt bolag.",
              "Klicka högst upp i programmet, på bolagsnamnet eller räkenskapsåret, och välj <strong>Export</strong>.",
              "Välj filtypen <strong>SIE4 – Transaktioner</strong>.",
              "Ange datumintervall: räkenskapsårets första och sista dag.",
              "Välj om alla konton, kostnadsställen och projekt ska följa med, och bocka i de verifikationsserier som ska ingå. Ta med alla.",
              "Klicka på <strong>Exportera</strong> och spara filen."],
     "tips": ["En SIE-fil innehåller alltid högst ett räkenskapsår. Vill du granska flera år tar du ut en fil per år.",
              "SIE4 är den typ som innehåller verifikationerna. SIE1–SIE3 innehåller bara saldon och räcker inte för en granskning."],
     "kallor": [("Fortnox: Exportera SIE-fil", "https://support.fortnox.se/produkthjalp/bokforing/exportera-sie-fil"),
                ("Fortnox: Exportera SIE-fil i Fortnox Bokföring", "https://support.fortnox.se/supportplay/bokforing/exportera-sie-fil-i-fortnox-bokforing")]},
    {"slug": "sie-fil-spiris", "namn": "Spiris Bokföring & Fakturering (f.d. Visma eEkonomi)",
     "ingress": "Visma eEkonomi heter sedan 2025 Spiris Bokföring & Fakturering. SIE-exporten ligger under inställningarna för import och export, och du exporterar ett räkenskapsår i taget.",
     "steg": ["Gå till <strong>Inställningar – Import och export</strong>.",
              "Välj <strong>SIE – import och export av bokföringsdata</strong>.",
              "Välj att göra en ny export.",
              "Välj det räkenskapsår du vill granska.",
              "Klicka på exportera och spara filen."],
     "tips": ["Programmet exporterar SIE 4, som innehåller alla verifikationer.",
              "Utanför Sverige heter programmet Visma eAccounting, så du kan stöta på det namnet i hjälptexter."],
     "kallor": [("Visma eEkonomi: Exportera bokföringsdata (SIE)", "https://help.visma.net/se_en/eaccounting/content/online-help/settings-import-export-accounting-data-export.htm"),
                ("Spiris: Byt från Visma-program (menynamn för SIE)", "https://www.spiris.se/support/kom-igang/dataflytt/byt-fran-visma-progam"),
                ("Spiris: Visma Spcs blir Spiris", "https://www.spiris.se/support/visma-spcs-blir-spiris")]},
    {"slug": "sie-fil-visma-administration", "namn": "Visma Administration och Visma Bokföring",
     "ingress": "I de installerade programmen Visma Administration och Visma Bokföring, som numera supportas av Spiris, ligger SIE-exporten under Arkiv.",
     "steg": ["Öppna rätt företag och se till att rätt räkenskapsår är valt.",
              "Välj <strong>Arkiv – Export – SIE</strong>.",
              "Välj <strong>SIE 4</strong>, som innehåller alla verifikationer för bokföringsåret.",
              "Klicka <strong>OK</strong>. Programmet föreslår mappen SIE och företagsnamnet som filnamn. Svara ja om programmet frågar om mappen ska skapas.",
              "Klicka <strong>Spara</strong> och sedan <strong>OK</strong> när exporten är klar."],
     "tips": ["Välj vanlig SIE 4, inte SIE 4B. 4B tar även med borttagna verifikationsrader.",
              "Exportera ett räkenskapsår i taget."],
     "kallor": [("Spiris: Export SIE, Visma Administration 500", "https://support.spiris.se/visma-administration-500/content/online-help/export-sie.htm"),
                ("Spiris: Export SIE, Visma Administration 1000", "https://support.spiris.se/visma-administration-1000/content/online-help/export-sie.htm"),
                ("Spiris: Export av SIE, Visma Bokföring", "https://support.spiris.se/visma-bokforing/content/visma-bokforing/bokforing/export-av-sie.htm")]},
    {"slug": "sie-fil-bokio", "namn": "Bokio",
     "ingress": "I Bokio exporterar du SIE-filen från inställningarna. Filen blir en SIE4-fil som slutar på .se.",
     "steg": ["Gå till <strong>Inställningar → Exportera data</strong>.",
              "Leta upp det räkenskapsår du vill granska.",
              "Klicka på de tre prickarna (…) bredvid räkenskapsåret.",
              "Välj <strong>SIE 4</strong> och spara filen."],
     "tips": ["Exporten ändrar ingenting i bokföringen.",
              "Enligt Bokio krävs en aktiv prisplan för att exportera bokföringen."],
     "kallor": [("Bokio: Hur exporterar jag SIE-filer?", "https://www.bokio.se/hjalp/bokforing/import-och-export/hur-exporterar-jag-sie-filer/")]},
    {"slug": "sie-fil-bjorn-lunden", "namn": "Björn Lundén (BL Administration)",
     "ingress": "I det installerade programmet BL Administration ligger SIE-exporten under Arkiv. Där väljer du SIE-typ, räkenskapsår och var filen ska sparas.",
     "steg": ["Välj <strong>Arkiv – Export – SIE (bokföring)</strong>.",
              "Välj <strong>SIE-4 – Årssaldon och transaktioner</strong>.",
              "Välj <strong>Räkenskapsår</strong>. Du exporterar ett år åt gången.",
              "Kontrollera mapp och filnamn längst ned. Standardmappen är C:\\SIE och filnamnet föreslås automatiskt.",
              "Klicka på <strong>Exportera</strong>."],
     "tips": ["Filen slutar på .SE. Låt ändelsen vara kvar.",
              "Använder du Björn Lundéns webbtjänst i stället: sök efter Export under Inställningar, eller fråga Björn Lundéns support."],
     "kallor": [("Björn Lundén: Export", "https://support.bjornlunden.se/guide/export")]},
    {"slug": "sie-fil-accounted", "namn": "Accounted",
     "ingress": "I Accounted ligger SIE-exporten under Bokföring. Filen innehåller kontoplan, in- och utgående balanser och alla verifikationer.",
     "steg": ["Gå till <strong>Bokföring</strong>.",
              "Välj <strong>Importera/Exportera</strong> och fliken <strong>Exportera</strong>.",
              "Klicka på <strong>SIE 4</strong>.",
              "Välj räkenskapsår.",
              "Klicka <strong>Ladda ner SIE</strong>."],
     "tips": ["Filen heter export_ följt av ett nummer och slutar på .se.",
              "Det går att utesluta bokslutsverifikationen innan nedladdning. För en granskning av hela året tar du med den."],
     "kallor": [("Accounted: SIE4-export och import steg för steg", "https://www.accounted.se/blogg/sie4-export-och-import-steg-for-steg")]},
    {"slug": "sie-fil-briox", "namn": "Briox",
     "ingress": "I Briox ligger SIE-exporten i vänstermenyn under Exporter. SIE4 är förvald.",
     "steg": ["Gå till <strong>Exporter – Exportera SIE-fil</strong> i vänstermenyn.",
              "Kontrollera att <strong>SIE4</strong> är vald. Den är förvald.",
              "Ange datumintervall: räkenskapsårets första och sista dag.",
              "Välj om alla konton, kostnadsställen och projekt ska ingå, och markera alla verifikationsserier.",
              "Klicka på <strong>Exportera</strong> längst ned."],
     "tips": ["En grå ruta framför en verifikationsserie betyder att serien är tom."],
     "kallor": [("Briox: Exportera SIE-fil", "https://support.briox.se/hc/sv/articles/21136921826972-Exportera-SIE-fil")]},
]
